repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.1.1
  hooks:
  - id: black
    pass_filenames: true

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
  - id: ruff

- repo: local
  hooks:
  - id: cargo fmt
    name: cargo fmt
    entry: cargo fmt --
    language: system
    types: [rust]
  
  # could not make this work
  # - id: cargo clippy
  #   name: cargo clippy
  #   entry: cargo clippy --fix --lib -p pyift --allow-staged --all--targets
  #   language: system
  #   types: [rust]
