repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.1.1
  hooks:
  - id: black
    pass_filenames: true

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
  - id: ruff
